{{- range .Values.jwtSecrets }}
{{- if .create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ default $.Values.namespace .namespace }}
type: {{ default "Opaque" .type }}
stringData:
  {{- toYaml .stringData | nindent 2 }}
{{- end }}
{{- end }}
