apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata: 
  name: argocd-repo-creds
  namespace: argocd
  labels: 
    argocd.argoproj.io/secret-type: repository
    creationTimestamp: null
  spec: 
    template: 
      metadata: 
        name: argocd-repo-creds
        namespace: argocd
        creationTimestamp: null
    encryptedData: 
      sshPrivateKey: "AgDbeuAlH0wyCCJxYlqxiS7OWtXB14w4WsRr8usrZYsjtgFic3CXhn88yWOFDLQow5xwWGgwuyXnJILHB1R6/uK71ogTT6SY2z7l1uEJMtVHF2bWmXJtGsTKkC+fR/AgWBOkSCGPhL3+uiEhIR4eUt6UJ1RwM+E9f7Fh62qqMcLnTge1fdwrLATpNGIStWhFOsIFp/NgVDVdqF40BkYpFG9Y38NmWr2D40YgSMTfmGkir0xLF8ZGzejcjrm7oa7xpneNsfaV444beSn4tFjFMWra9D/kHZNEX9uc+kZG3hznQN51WYOAz/DE9VFn5CCpcO9aZexOO5EpHeV6zjW0XQPL/dMUW5ziZPdMmKCIxmAr3qwMW64QY1xSzLjnq2ecAldd97jnDYj8R6EUMK1zQEBNnwX+NcxNHRyzkY/yVlDd9baMB0inuMy0iSPREOrVZUWJKn8CEouNhG1TTj1ogvFZtlQQxcXQDKYpR1VOsfw4tHGwoArvL2QZnY/W5dIzDuxR4woivq1TwfmdZt269gFVysTwNbaEbH6IA6r6L8rCDOqX4EKQyurRa+f+bzzurt3X6x6UJcvbDMpwAET6EKTQGq7V0ca2qEaxsZsg4p73f2DM3z7Op9xxYl8W30FBrdCmUzRScsmtuVjNBgWbs/G9dS66L+TGhf/Aq2XBv1lr0yMl1NmJttnFXBiifeUnidbFHanm++yL32S5yaZNbaRP5v3zaOP6oMDV5o9DXrRCOaJ7jmb8oUzh2QCjZUNDfKdQf5pjWCBiG1flHs2clz7vnvMh2gz5Vbz8BKn0gEj/1/UN+//KKixCft9wmRJYeOTGPALANrHxIeIdLzX29I5yNpD7HxkVCmyKMMuQj7rwhMV/8prYhvL9JZYuu2ARng8/ilzT3ZUrVtBo53RuhoV6VdssX0to/knH4ChFI8j7rw9ZoiR7wt0R8uZ6BFgbkVb2ZBzNJcfMQlT4bnWF56bShEqjtGLBnO89R99X3PGFK1BVQ6RjucHoGzV+0xqeriSD9sF8A86t6NBLb1y2ri99WkyEmZHi8tyHP4/uZYFnWKsvJmBp+ELf+2Lf6+BZrKbhcZYBiq/isUKVn5tK59y6oiZwmvgMbXGJCeJTjKUVld3XQdFve47HVKFUZm7Uzemnq0YKVvWS+oPTLHf6MjPsOAMy767sYXrTWoxYx7UvKjt4lRc3FMMWu6fFE8UarTsKCqydAK50lPbBdT44lv0="

