apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  sourceRepo:
    - 'git@github.com:Dango-go/Market-infrastructure.git'   # Create if source this repo 

  # Resource which can deploy with type ClusterRole
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace  
  
  # Resource which can deploy with type ns
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"  