apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: application-monitor
  namespace: application
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - application  

  selector:
    matchLabels:
      application: service

  endpoints:

    - port: tcp-prometheus
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s 
 
      relabelings:
        - separator: ;
          regex: __meta_kubernetes_pod_name  # source labels
          replacement: $1
          sourceLabels:  # every parameters in settings will with label __meta__
            - __meta_kubernetes_pod_name  # only pod name label
          targetLabel: kubernetes_pod_name

    - port: metrics 
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      relabelings:
        - separator: ;
          regex: __meta_kubernetes_pod_name
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: kubernetes_pod_name