apiVersion: postgresql.cnpg.io/v1
kind: Cluster   
metadata:
  name: postgres-cluster
  namespace: storage
  labels:
    environment: development
spec:  
  instances: 3
 
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2

  resources:
    requests:
      cpu: "250m" # Milicores
      memory: "1.5Gi"
    limits:
      cpu: "400m"
      memory: "1.5Gi" 

  storage:
    size: 30Gi  # Aoutcreate pvc 
 
    storageClass: premium-rwo

 
  walStorage:
    size: 3Gi
    storageClass: premium-rwo
 
  
  postgresql:
    parameters:
 
      shared_buffers: "300MB"        
      work_mem: "6MB"
      maintenance_work_mem: "128MB"
      effective_cache_size: "270MB"  
      max_connections: "80"
      
 
      log_destination: "csvlog"
      logging_collector: "on"
      log_statement: "ddl"         
      log_min_duration_statement: "1000"  
 
  affinity:
    enablePodAntiAffinity: true
    topologyKey: topology.kubernetes.io/zone  
 
  monitoring:
    enablePodMonitor: true  
 
  bootstrap:
    initdb:
      database: default  
      owner: default           
 
      secret:
        name: default
 
  serviceAccountName: postgres-backup-sa  # Local SA for leader and replicas pods with postgres
  backup:
 
    retentionPolicy: "30d"
    barmanObjectStore:
 
      destinationPath: "s3://storage-dango-v1/postgres-cluster/"
      endpointURL: "https://storage.googleapis.com"
      #googleCredentials:
        #gkeServiceAccount:
          #name: pg-backup-sa
      s3Credentials:
        accessKeyId:
          name: aws-s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-s3-creds
          key: ACCESS_SECRET_KEY
 
      wal:
        compression: gzip
        