apiVersion: v1
kind: Secret
metadata:
  name: analytics-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: analytics
---
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: api-gateway
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: auth
---
apiVersion: v1
kind: Secret
metadata:
  name: cart-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: cart
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: catalog
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: inventory
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: notification
---
apiVersion: v1
kind: Secret
metadata:
  name: order-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: order
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: payment
---
apiVersion: v1
kind: Secret
metadata:
  name: pricing-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: pricing
---
apiVersion: v1
kind: Secret
metadata:
  name: recommendation-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: recommendation
---
apiVersion: v1
kind: Secret
metadata:
  name: review-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: review
---
apiVersion: v1
kind: Secret
metadata:
  name: search-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: search
---
apiVersion: v1
kind: Secret
metadata:
  name: shipping-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: shipping
---
apiVersion: v1
kind: Secret
metadata:
  name: user-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: user
---
apiVersion: v1
kind: Secret
metadata:
  name: wishlist-custom-secret
  namespace: storage
type: Opaque
stringData:
  password: wishlist
