apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
  namespace: storage
type: Opaque
stringData:
  password-1: analytics

---
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: storage
type: Opaque
stringData:
  password-1: api-gateway

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: storage
type: Opaque
stringData:
  password-1: auth

---
apiVersion: v1
kind: Secret
metadata:
  name: cart-secret
  namespace: storage
type: Opaque
stringData:
  password-1: cart

---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
  namespace: storage
type: Opaque
stringData:
  password-1: catalog

---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-secret
  namespace: storage
type: Opaque
stringData:
  password-1: inventory

---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: storage
type: Opaque
stringData:
  password-1: notification

---
apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: storage
type: Opaque
stringData:
  password-1: order

---
apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: storage
type: Opaque
stringData:
  password-1: payment

---
apiVersion: v1
kind: Secret
metadata:
  name: pricing-secret
  namespace: storage
type: Opaque
stringData:
  password-1: pricing

---
apiVersion: v1
kind: Secret
metadata:
  name: recommendation-secret
  namespace: storage
type: Opaque
stringData:
  password-1: recommendation

---
apiVersion: v1
kind: Secret
metadata:
  name: review-secret
  namespace: storage
type: Opaque
stringData:
  password-1: review

---
apiVersion: v1
kind: Secret
metadata:
  name: search-secret
  namespace: storage
type: Opaque
stringData:
  password-1: search

---
apiVersion: v1
kind: Secret
metadata:
  name: shipping-secret
  namespace: storage
type: Opaque
stringData:
  password-1: shipping

---
apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: storage
type: Opaque
stringData:
  password-1: user

---
apiVersion: v1
kind: Secret
metadata:
  name: wishlist-secret
  namespace: storage
type: Opaque
stringData:
  password-1: wishlist
