apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: analytics-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: analytics
  passwordSecret:
    name: analytics-custom-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: api-gateway-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: api-gateway
  passwordSecret:
    name: api-gateway-custom-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: auth-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: auth
  passwordSecret:
    name: auth-custom-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: cart-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: cart
  passwordSecret:
    name: cart-custom-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: catalog-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: catalog
  passwordSecret:
    name: catalog-custom-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: inventory-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: inventory
  passwordSecret:
    name: inventory-custom-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: notification-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: notification
  passwordSecret:
    name: notification-custom-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: order-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: order
  passwordSecret:
    name: order-custom-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: payment-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: payment
  passwordSecret:
    name: payment-custom-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: pricing-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: pricing
  passwordSecret:
    name: pricing-custom-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: recommendation-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: recommendation
  passwordSecret:
    name: recommendation-custom-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: review-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: review
  passwordSecret:
    name: review-custom-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: search-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: search
  passwordSecret:
    name: search-custom-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: shipping-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: shipping
  passwordSecret:
    name: shipping-custom-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: user-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: user
  passwordSecret:
    name: user-custom-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: wishlist-user
  namespace: storage
spec:
  cluster:
    name: postgres-cluster
  name: wishlist
  passwordSecret:
    name: wishlist-custom-secret