apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup-sa
  namespace: storage
  annotations:
    iam.gke.io/gcp-service-account:  pg-backup-sa@market-infrastructure.iam.gserviceaccount.com