apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: app   # App place 
spec:
  project: default
  source:
    repoURL: git@github.com:Dango-go/Market-infrastructure.git 
    targetRevision: HEAD  
    path: gitops-manifests/platform/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx # Place deployment