apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: databases
  namespace: app   
spec:
  project: default
  source:
    repoURL: git@github.com:Dango-go/Market-infrastructure.git 
    targetRevision: HEAD  
    path: gitops-manifests/database
  destination:
    server: https://kubernetes.default.svc
    namespace: storage  