apiVersion: v1
kind: Secret
metadata:
  name: jwt-token-private   
  namespace: application
type: Opaque
stringData:
  username: "admin"
  private_key.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5wIqC23sOpA96
    Gtac4TR4+9mTnNr8/juXl3a3w+PvgMCuwh17+XQSqx6igyVAseEz3EwKVFsHE9Nt
    IPlkJ3ZbxG7cHVZhZqvsa8aMLtiR/gZ8WKrLszwYDZtWqYownrec5SPfXm0I+h73
    QUG6L4dMcyvlij5ZRlqcj4+Zz3R59rxzDMm3GBVZGv4Qn8rvpry8ka6ERAKdbZ3B
    G0Ni43bRpZqtwZ44WQDqhmG9ExPF1bg4mqa5DdcXbF3LaFLChvSV8mAHDypPDvbr
    PGebw19cCHhsZ9FOOznQy/TmC/KxYxRAo6840YVrRYl7Psuptu3estaZZ6Rra76s
    eLFDUb0NAgMBAAECggEAAWf9cOUcTSEoGrotyVxrbduZIH3CI99WghlBTj3lCn41
    kBtZJvXPWiwM2qB9mB+XueMkleSn3omY268OBvFTbQezal9XtPur6ltcoLzGYqtx
    Vi61Gk1Js5fqHEbtk3kmy08i4qLfyCmkzfr/PWm8FpAoiHFoniXmj+AGr3kLY6n4
    Bh2L7AIMtLk1G4DDLleNdfwsZkdVj7wDi6TdCDd5ocqXMaLlinsG4JP282WTSuKn
    dgVBW3asT7GWH5WbIQ7+Q9p2McLNyLD6EDHjtgLaH5B0OwOpVuVhtvAz6p79zvss
    pcZl4WN94IZ/7B7BoeRga3k9GsZjD1iTpZpEaUi8EQKBgQDf047p3r2iXZETAmTc
    zR/h/T1HwaYx4a2jTbK1I1C9n2dAqxRxUqVi+vA0SIXu/oo49K+LmmfbRFYHmvzC
    fN+YBE2V9yMdRsaybJbLaRRqJDZ09xD5K2pclAYL3lHaxvPH6rUzk7nThYItCd0q
    P1v4QUTXvjyOTLNjs27t6BJXnQKBgQDUc+l3cdvsK3Dk6bDsj8uCrlGjK2JQ5DdB
    cjy02TfYSkeW7+zhMmeu0sI8hNzwBmbLaXHpoUNGREiyUaPhzHpCzkxYUOiLes+c
    Xf4FZTtSgteF3HLTbw2beHgg/aBx+B3+LQCBWEbe6Ikf9BsGfHP+6IYigmUIlY4t
    YztgYCVYMQKBgCHtYYZVuwz3fdwRytQlS6XnyvgrhFOfT8CnMGWAmuaDWRVWWVzs
    GCGuw+ZI7/RQJQeJH2rb1s5Hx3qTpaidYQ8b597JfUscxVWaXCktHmkQYCjOooYC
    bLbnwRrfcizlZ2JwU1MkG1DSte65xgp3XCt/ST4ime8/9Rkxw6jQOqeJAoGAAQi7
    ZzBvsJuZhhO5H72ncPBmR1QLu3cQ6cmjkAHKqsvZw1tRnNsA9DHkbiT7alOtpmnR
    +yAk0q+8ZtnM4Wl8YtzcNEXYi+1CG3G9rcsLWeB3KhijmnHc8BfLBeYWJNffVYBk
    kzyZw7YADN7ETujGK8R3+q0Fzt/jfEcSX+q349ECgYEAkTxqgDwJETVxuxZAgHXX
    BL9N+e1Ce9Xj10t0iMq28OXi2MWlo5HgzBlh2CEN7hws06psFQQrBf9f2rCqsCVI
    jv+gbpIUzs02HRyQ94l1e+ktmf+J6mkIRWi8rqJzF9/VH2rk9HdBypv/gob1CUbO
    9SE8D8jX2s5aXT4ullgGs2k=
    -----END PRIVATE KEY-----
